export const passwordfacts = [
  "Nearly 80% of the cloud services allow users to set up weak passwords",
  "Nearly 30% of the users reuse the same password on multiple accounts",
  "20 most common passwords make for 10.3% of the passwords in use",
  "70% of users have more than 10 password-protected accounts",
  "This year, the average number of accounts per user will be 207",
  "Only 1% of the web services ask users to create an extremely safe password",
  "40% of organizations store passwords in a Word document or a spreadsheet",
  "66% of people use only 1 or 2 passwords for all their accounts",
  "The usually prescribed minimum length of passwords is 12 or more",
  "It seems the younger generation doesn’t pay much attention to password security",
  "There is a 50% chance that a password contains at least one vowel",
  "People are 3 times more likely to use their pet’s name as password rather than that of a family member",
  "A person usually changes the password every 2.5 to 3 years",
  "Someone created a computer capable of guessing 350 billion passwords per second",
  "There are roughly more than a million brute force attack on WordPress sites each hour",
  "48% of people have shared a password with someone else",
  "68% of the executives of companies that experienced significant breaches indicated that those could have been prevented",
  "First Thursday of each May is World Password Day",
  "“123456” is the most commonly used password",
];
